class ShipmentFileType:
    fields = {
        "ARRIVAL_DATE": {"column_no": 0, "validation_rules": ["exist", "date"]},
        "BILL_OF_LADING_NO": {"column_no": 1, "validation_rules": ["text"]},
        "DECLARATION_NUMBER": {"column_no": 2, "validation_rules": ["text"]},
        "HS_CODE": {"column_no": 3, "validation_rules": ["exist", "hs_code"]},
        "HS_CODE_DESCRIPTION": {"column_no": 4, "validation_rules": ["text"]},
        "PRODUCT_DETAILS": {"column_no": 5, "validation_rules": ["text"]},
        "IMPORTER_TA_CODE": {"column_no": 6, "validation_rules": ["exist", "ta_code"]},
        "EXPORTER_TA_CODE": {"column_no": 7, "validation_rules": ["exist", "ta_code"]},
        "FOB_VALUE": {"column_no": 8, "validation_rules": ["float"]},
        "FOB_CURRENCY": {"column_no": 9, "validation_rules": ["text"]},
        "FREIGHT_AMOUNT": {"column_no": 10, "validation_rules": ["float"]},
        "INSURANCE_AMOUNT": {"column_no": 11, "validation_rules": ["float"]},
        "F_I_CURRENCY": {"column_no": 12, "validation_rules": ["text"]},
        "CIF_VALUE": {"column_no": 13, "validation_rules": ["float"]},
        "CIF_CURRENCY": {"column_no": 14, "validation_rules": ["text"]},
        "STATISTICAL_VALUE_USD": {"column_no": 15, "validation_rules": ["float"]},
        "UNIT_PRICE": {"column_no": 16, "validation_rules": ["float"]},
        "NET_WEIGHT": {"column_no": 17, "validation_rules": ["float"]},
        "NET_WEIGHT_UNIT": {"column_no": 18, "validation_rules": ["text"]},
        "GROSS_WEIGHT": {"column_no": 19, "validation_rules": ["float"]},
        "GROSS_WEIGHT_UNIT": {"column_no": 20, "validation_rules": ["text"]},
        "QUANTITY": {"column_no": 21, "validation_rules": ["float"]},
        "QUANTITY_UNIT": {"column_no": 22, "validation_rules": ["text"]},
        "PACKAGE_AMOUNT": {"column_no": 23, "validation_rules": ["float"]},
        "PACKAGES_UNIT": {"column_no": 24, "validation_rules": ["text"]},
        "INCOTERMS": {"column_no": 25, "validation_rules": ["text"]},
        "PAYMENT_TYPE": {"column_no": 26, "validation_rules": ["text"]},
        "TRANSPORT_TYPE": {"column_no": 27, "validation_rules": ["text"]},
        "REGIME": {"column_no": 28, "validation_rules": ["text"]},
        "BRAND_NAME": {"column_no": 29, "validation_rules": ["text"]},
        "MANUFACTURING_COMPANY": {"column_no": 30, "validation_rules": ["text"]},
        "COUNTRY_OF_ORIGIN": {
            "column_no": 31,
            "validation_rules": ["exist", "country"],
        },
        "PORT_OF_ARRIVAL": {"column_no": 32, "validation_rules": ["text"]},
        "PORT_OF_DEPARTURE": {"column_no": 33, "validation_rules": ["text"]},
        "CONDITION_New_Used": {"column_no": 34, "validation_rules": ["text"]},
        "NOTIFY_PARTY": {"column_no": 35, "validation_rules": ["text"]},
        "NOTIFY_ADDRESS": {"column_no": 36, "validation_rules": ["text"]},
        "TRANSPORT_COMPANY": {"column_no": 37, "validation_rules": ["text"]},
        "CONTAINER_COUNT": {"column_no": 38, "validation_rules": ["float"]},
        "TOTAL_TEUS": {"column_no": 39, "validation_rules": ["float"]},
        "EXPORT_DATA_TYPE": {"column_no": 40, "validation_rules": ["short"]},
        "IMPORT_DATA_TYPE": {"column_no": 41, "validation_rules": ["short"]},
        "ITEM_NO": {"column_no": 42, "validation_rules": ["float"]},
        "DATA_TYPE": {"column_no": 43, "validation_rules": ["text"]},
        "VESSEL_NAME": {"column_no": 44, "validation_rules": ["text"]},
        "RECORD_ID": {"column_no": 45, "validation_rules": ["exist"]},
    }
