class ArgentinaTypes:
    IMPORT_COLUMNS = [
        "DAY",
        "MONTH",
        "YEAR",
        "IMPORT_ID",
        "OPER_TYPE",
        "CUSTOMS",
        "IMPORTER_ID",
        "IMPORTER",
        "SALES_COUNTRY",
        "TRANS_TYPE",
        "ORIGIN_PORT",
        "INCOTERMS",
        "TOTAL_FOB",
        "TOTAL_FREIGHT",
        "TOTAL_INSURANCE",
        "TOTAL_CIF",
        "PACKAGES",
        "G_WEIGHT",
        "ITEM_NUMBER",
        "ORIGIN_COUNTRY",
        "QUANTITY",
        "UNIT_OF_QUANTITY",
        "ITEM_FOB",
        "ITEM_FREIGHT",
        "ITEM_INSURANCE",
        "HS_CODE",
        "PRODUCT_DESC",
        "ITEM_CIF",
        "SUBITEM_NUMBER",
        "BRAND",
        "VARIETY",
        "ATTRIBUTES",
        "SUBITEM_FOB",
        "SUBITEM_QUANTITY",
    ]

    IMPORT_CHANGE_COLUMN_NAMES = {
        "IMPORT_ID": "DECLARATION_NUMBER",
        "OPER_TYPE": "REGIME",
        "CUSTOMS": "PORT_OF_ARRIVAL",
        "IMPORTER_ID": "IMPORTER_TAX_ID",
        "IMPORTER": "IMPORTER_NAME",
        "SALES_COUNTRY": "EXPORTER_COUNTRY",
        "TRANS_TYPE": "TRANSPORT_TYPE",
        "ORIGIN_PORT": "PORT_OF_DEPARTURE",
        "PACKAGES": "PACKAGE_AMOUNT",
        "G_WEIGHT": "GROSS_WEIGHT",
        "ORIGIN_COUNTRY": "COUNTRY_OF_ORIGIN",
        "UNIT_OF_QUANTITY": "QUANTITY_UNIT",
        "ITEM_FOB": "FOB_VALUE",
        "ITEM_FREIGHT": "FREIGHT_AMOUNT",
        "ITEM_INSURANCE": "INSURANCE_AMOUNT",
        "PRODUCT_DESC": "PRODUCT_DETAILS",
        "ITEM_CIF": "CIF_VALUE",
        "BRAND": "BRAND_NAME",
    }

    IMPORT_ADD_COLUMN = {
        "ARRIVAL_DATE": {"type": "date", "default": None},
        "PACKAGES_UNIT": {"type": "str", "default": "Pieces"},
        "GROSS_WEIGHT_UNIT": {"type": "str", "default": "Kilogram"},
        "FOB_CURRENCY": {"type": "str", "default": "USD"},
        "F_I_CURRENCY": {"type": "str", "default": "USD"},
        "CIF_CURRENCY": {"type": "str", "default": "USD"},
        "IMPORTER_COUNTRY": {"type": "str", "default": "AR"},
        "EXPORT_DATA_TYPE": {"type": "int", "default": 4},
        "IMPORT_DATA_TYPE": {"type": "int", "default": 1},
        "DATA_TYPE": {"type": "str", "default": "Custom"},
        "IMPORTER_TA_CODE": {"type": "str", "default": None},
        "EXPORTER_TA_CODE": {"type": "str", "default": None},
        "RECORD_ID": {"type": "uuid", "default": "uuid"},
    }

    EXPORT_COLUMNS = [
        "DAY",
        "MONTH",
        "YEAR",
        "EXPORT_ID",
        "OPER_TYPE",
        "EXPORTER",
        "CUSTOMS",
        "HS_CODE",
        "PRODUCT_DESC",
        "BRAND",
        "VARIETY",
        "ATTRIBUTES",
        "DEST_COUNTRY",
        "TOTAL_FOB",
        "TOTAL_CIF",
        "QUANTITY",
        "UNIT_OF_QUANTITY",
        "PACKAGES",
        "ITEM_NUMBER",
        "ITEM_FOB",
        "ITEM_CIF",
        "G_WEIGHT",
        "TRANS_TYPE",
        "INCOTERMS",
        "SUBITEM_NUMBER",
        "SUBITEM_FOB",
        "SUBITEM_QUANTITY",
    ]

    EXPORT_CHANGE_COLUMN_NAMES = {}

    EXPORT_ADD_COLUMN = {}
